name: Security

on:
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - 'doc/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@v0.0.8
        with:
          go-version: 1.19
          vulncheck-version: latest
          skip-upload: true
          package: cmd/
          fail-on-vuln: false
        env:
          DEBUG: "true"

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: govulncheck-report.sarif
